export const DASHBOARD_DATA = {
  "generatedAt": "2026-09-20T10:24:43.504Z",
  "sources": {
    "notes": {
      "title": "IETLS",
      "url": "https://docs.google.com/document/d/1BB015rszjlVB1LO_G--df47DAOlRbsqdERx3Jg8OHPU/edit"
    },
    "tracker": {
      "title": "ielts-tracker",
      "url": "https://docs.google.com/spreadsheets/d/1msuomUevR2EIg3LESc_2OqixJIyfu70klBsPRAyyVco/edit"
    },
    "book": {
      "title": "Complete IELTS Bands 6.5-7.5",
      "url": "https://drive.google.com/file/d/1v3C1DpOz3vwyisskFh7j810mtP12prEC/view"
    }
  },
  "goals": {
    "baseline": 5,
    "target": 6.5,
    "stretch": 7.5,
    "completedSessions": 15,
    "totalSessions": 168
  },
  "bugs": [
    {
      "stt": 1,
      "date": "2026-08-24",
      "skill": "Listening",
      "id": "LIST_01",
      "original": "alexsandrovna / Hapwortz",
      "cause": "Phát âm nguyên âm ngắn nhầm (E vs S) và phụ âm ghép (P vs B).",
      "fix": "Alexandrovna / Hepworth",
      "example": "Đánh vần tên riêng trong Section 1.",
      "status": "DONE"
    },
    {
      "stt": 2,
      "date": "2026-08-24",
      "skill": "Listening",
      "id": "LIST_02",
      "original": "next month",
      "cause": "Bị đánh lừa bởi từ \"next month\", bỏ lỡ ngày cụ thể đã chốt ở vế sau.",
      "fix": "21st of July",
      "example": "Bẫy distractors ngày tháng.",
      "status": "DONE"
    },
    {
      "stt": 3,
      "date": "2026-08-24",
      "skill": "Grammar / Vocab",
      "id": "PREP_01",
      "original": "experience for/in",
      "cause": "Chưa nắm vững cụm giới từ đi sau danh từ experience.",
      "fix": "experience in (business)",
      "example": "I have 3 years of experience in software development.",
      "status": "DONE"
    },
    {
      "stt": 4,
      "date": "2026-08-28",
      "skill": "Grammar / Vocab",
      "id": "PREP_02",
      "original": "capable of (sai) / impressed in",
      "cause": "Nhầm lẫn dependent prepositions.",
      "fix": "capable of / impressed with/by",
      "example": "This system is capable of handling millions of requests.",
      "status": "DONE"
    },
    {
      "stt": 5,
      "date": "2026-08-28",
      "skill": "Grammar / Vocab",
      "id": "PREP_03",
      "original": "belief to / blaming on",
      "cause": "Nhầm lẫn dependent prepositions.",
      "fix": "belief in / blaming for",
      "example": "Blaming the database crash on the old legacy query.",
      "status": "OPEN"
    },
    {
      "stt": 6,
      "date": "2026-08-28",
      "skill": "Grammar / Vocab",
      "id": "TENSE_01",
      "original": "was already begin",
      "cause": "Chưa thuộc dạng phân từ 3 và cấu trúc quá khứ hoàn thành.",
      "fix": "had already begun",
      "example": "The automated backup had already begun before the server crashed.",
      "status": "OPEN"
    },
    {
      "stt": 7,
      "date": "2026-08-28",
      "skill": "Grammar / Vocab",
      "id": "TENSE_02",
      "original": "weren't alter",
      "cause": "Lỗi chia thể phủ định của động từ thường ở quá khứ đơn.",
      "fix": "did not alter",
      "example": "The configuration update did not alter the core functionality.",
      "status": "OPEN"
    },
    {
      "stt": 8,
      "date": "2026-08-27",
      "skill": "Speaking",
      "id": "SPEAK_01",
      "original": "get used to be",
      "cause": "Quên quy tắc get used to + V-ing (quen với việc gì).",
      "fix": "get used to being (lazy)",
      "example": "I am getting used to being a FullStack Developer.",
      "status": "OPEN"
    },
    {
      "stt": 9,
      "date": "2026-09-01",
      "skill": "Reading",
      "id": "READ_01",
      "original": "TRUE",
      "cause": "Lỗi dịch sai (Runtime Exception). Nghi ngờ Heredia nghĩ là hóa thạch.",
      "fix": "FALSE (Guillermo Heredia believed it was a petrified tree trunk, not a dinosaur fossil)",
      "example": "Believed a tree trunk, actually a dinosaur. (Like mistaking a legacy text log file for a core dump)",
      "status": "DONE"
    },
    {
      "stt": 10,
      "date": "2026-09-06",
      "skill": "Reading",
      "id": "READ_02",
      "original": "therapod",
      "cause": "Lỗi từ vựng, Lỗi dịch sai (Runtime Exception). Misread diagram label pointing to dimensions.",
      "fix": "three / 3 metres (high)",
      "example": "Reading a system spec diagram's dimensions incorrectly. (Misreading port numbers or scaling metrics)",
      "status": "DONE"
    },
    {
      "stt": 11,
      "date": "2026-09-06",
      "skill": "Reading",
      "id": "READ_03",
      "original": "eight meters",
      "cause": "Lỗi từ vựng, Lỗi dịch sai. Pointer mismatch (confused overall length with body part label).",
      "fix": "(bird-like) beak",
      "example": "Label pointer mismatch. (Like pointing to a function's return statement but reading overall length instead)",
      "status": "DONE"
    },
    {
      "stt": 12,
      "date": "2026-09-06",
      "skill": "Reading",
      "id": "READ_04",
      "original": "legs",
      "cause": "Lỗi không tìm ra paraphrase (Wrong Mapping). Failed to link treetops climbing evidence to curved claws.",
      "fix": "curved claws",
      "example": "Paraphrase mapping mismatch. (Like calling a generic Class instead of the specific child method to resolve tree climbing)",
      "status": "DONE"
    },
    {
      "stt": 13,
      "date": "2026-09-06",
      "skill": "Reading",
      "id": "READ_05",
      "original": "(asymmetrical vanes)",
      "cause": "Lỗi không tìm ra paraphrase (Wrong Mapping). Struggled to map 'asymmetrical vanes' to flight capability.",
      "fix": "asymmetrical vanes",
      "example": "Failing to map 'asymmetrical vanes' to flight capability in treetops.",
      "status": "DONE"
    },
    {
      "stt": 14,
      "date": "2026-09-06",
      "skill": "Reading",
      "id": "READ_06",
      "original": "ducks",
      "cause": "Lỗi từ vựng, Lỗi dịch sai (Phonetic Confusion). Wrote 'ducks' instead of homophone 'dusk'.",
      "fix": "(at) dusk",
      "example": "Phonetic / String spelling error. (Like typing 'float' as 'fleet', causing a compiler type mismatch)",
      "status": "DONE"
    },
    {
      "stt": 15,
      "date": "2026-09-06",
      "skill": "Reading",
      "id": "READ_07",
      "original": "(southern/ warmer)",
      "cause": "Lỗi không tìm ra paraphrase (Wrong Mapping). Failed to link climate/regional pointer to text.",
      "fix": "southern / warmer",
      "example": "Failing to map 'warmer climates' to regional variants.",
      "status": "DONE"
    },
    {
      "stt": 16,
      "date": "2026-09-06",
      "skill": "Reading",
      "id": "READ_08",
      "original": "foot chain",
      "cause": "Lỗi không tìm ra paraphrase (Wrong Mapping) / spelling. Wrote 'foot chain' instead of 'food chain'.",
      "fix": "food chain",
      "example": "Spelling bug on keyword. (Like using 'foot_chain' instead of 'food_chain' in database relationships)",
      "status": "DONE"
    },
    {
      "stt": 17,
      "date": "2026-09-07",
      "skill": "Listening",
      "id": "LIST_03",
      "original": "Bỏ trống (Q1)",
      "cause": "Không bắt được target keyword cần điền trong audio.",
      "fix": "eyeball",
      "example": "Tuần 3 – Bài 2/23, Q1",
      "status": "DONE"
    },
    {
      "stt": 18,
      "date": "2026-09-07",
      "skill": "Listening",
      "id": "LIST_04",
      "original": "sightstyle",
      "cause": "Nghe/ghi sai từ; không nhận ra từ vựng đúng trong ngữ cảnh.",
      "fix": "lifestyle",
      "example": "Tuần 3 – Bài 2/23, Q2",
      "status": "DONE"
    },
    {
      "stt": 19,
      "date": "2026-09-07",
      "skill": "Listening",
      "id": "LIST_05",
      "original": "use",
      "cause": "Chọn từ không khớp ý nghĩa/chức năng của chỗ trống.",
      "fix": "disability",
      "example": "Tuần 3 – Bài 2/23, Q3",
      "status": "DONE"
    },
    {
      "stt": 20,
      "date": "2026-09-07",
      "skill": "Listening",
      "id": "LIST_06",
      "original": "moon",
      "cause": "Phonetic confusion: nghe nhầm từ gần âm.",
      "fix": "mood",
      "example": "Tuần 3 – Bài 2/23, Q5",
      "status": "DONE"
    },
    {
      "stt": 21,
      "date": "2026-09-07",
      "skill": "Listening",
      "id": "LIST_07",
      "original": "emotion",
      "cause": "Không xác định đúng target keyword; chọn từ được nhắc đến thay vì đáp án cần điền.",
      "fix": "lighting / atmosphere",
      "example": "Tuần 3 – Bài 2/23, Q6",
      "status": "DONE"
    },
    {
      "stt": 22,
      "date": "2026-09-07",
      "skill": "Listening",
      "id": "LIST_08",
      "original": "A, E",
      "cause": "Bị distractor; chọn theo từ nghe thấy thay vì ý được xác nhận trong Multiple Choice.",
      "fix": "B, E",
      "example": "Tuần 3 – Bài 4/23, Q7–8",
      "status": "DONE"
    },
    {
      "stt": 23,
      "date": "2026-09-07",
      "skill": "Listening",
      "id": "LIST_09",
      "original": "A, D",
      "cause": "Bị distractor và không bám đúng đối tượng câu hỏi.",
      "fix": "B, D",
      "example": "Tuần 3 – Bài 4/23, Q9–10",
      "status": "DONE"
    },
    {
      "stt": 24,
      "date": "2026-09-08",
      "skill": "Reading",
      "id": "READ_09",
      "original": "VI",
      "cause": "Xác định sai main idea/heading của đoạn.",
      "fix": "IV",
      "example": "Tuần 3 – Bài 4/19–21, Q1",
      "status": "OPEN"
    },
    {
      "stt": 25,
      "date": "2026-09-08",
      "skill": "Reading",
      "id": "READ_10",
      "original": "ON",
      "cause": "Pointer mismatch; không lấy đúng từ/cụm từ từ passage cho Summary Completion.",
      "fix": "training trials",
      "example": "Tuần 3 – Bài 5/19, Q5",
      "status": "OPEN"
    },
    {
      "stt": 26,
      "date": "2026-09-08",
      "skill": "Reading",
      "id": "READ_11",
      "original": "three-phases",
      "cause": "Pointer mismatch; không xác định đúng thành phần được hỏi trong summary.",
      "fix": "position",
      "example": "Tuần 3 – Bài 5/19, Q6",
      "status": "OPEN"
    },
    {
      "stt": 27,
      "date": "2026-09-08",
      "skill": "Reading",
      "id": "READ_12",
      "original": "three-colors",
      "cause": "Không nhận ra paraphrase và chọn sai thông tin chi tiết.",
      "fix": "features / cues",
      "example": "Tuần 3 – Bài 5/19, Q7",
      "status": "OPEN"
    },
    {
      "stt": 28,
      "date": "2026-09-08",
      "skill": "Reading",
      "id": "READ_13",
      "original": "number",
      "cause": "Không đối chiếu đúng evidence line với từ cần điền.",
      "fix": "meaning / concept",
      "example": "Tuần 3 – Bài 5/19, Q8",
      "status": "OPEN"
    },
    {
      "stt": 29,
      "date": "2026-09-08",
      "skill": "Reading",
      "id": "READ_14",
      "original": "improve",
      "cause": "Không xác định đúng từ loại/ngữ nghĩa của chỗ trống.",
      "fix": "unhelpful",
      "example": "Tuần 3 – Bài 5/19, Q9",
      "status": "OPEN"
    },
    {
      "stt": 30,
      "date": "2026-09-08",
      "skill": "Reading",
      "id": "READ_15",
      "original": "C / D",
      "cause": "Pick from a list: đối chiếu sai evidence/paraphrase.",
      "fix": "A / C",
      "example": "Tuần 3 – Bài 6/19, Q10–11",
      "status": "OPEN"
    },
    {
      "stt": 31,
      "date": "2026-09-08",
      "skill": "Reading",
      "id": "READ_16",
      "original": "A / B",
      "cause": "Pick from a list: đối chiếu sai evidence/paraphrase.",
      "fix": "C / D",
      "example": "Tuần 3 – Bài 6/19, Q12–13",
      "status": "OPEN"
    },
    {
      "stt": 32,
      "date": "2026-09-10",
      "skill": "Speaking",
      "id": "SPEAK_02",
      "original": "Decide",
      "cause": "Không lấy đúng cụm diễn đạt hoàn chỉnh trong bài nói mẫu.",
      "fix": "decided to buy",
      "example": "Tuần 3 – Task 2/24, Q2",
      "status": "OPEN"
    },
    {
      "stt": 33,
      "date": "2026-09-10",
      "skill": "Speaking",
      "id": "SPEAK_03",
      "original": "old",
      "cause": "Chọn từ rời thay vì cụm mô tả đầy đủ.",
      "fix": "looks pretty old",
      "example": "Tuần 3 – Task 2/24, Q3",
      "status": "OPEN"
    },
    {
      "stt": 34,
      "date": "2026-09-10",
      "skill": "Speaking",
      "id": "SPEAK_04",
      "original": "People",
      "cause": "Không nhận ra cụm chủ ngữ chính xác trong bài nói mẫu.",
      "fix": "Some of my friends",
      "example": "Tuần 3 – Task 2/24, Q4",
      "status": "OPEN"
    },
    {
      "stt": 35,
      "date": "2026-09-10",
      "skill": "Speaking",
      "id": "SPEAK_05",
      "original": "Actually",
      "cause": "Nhầm chức năng discourse marker ở phần kết bài nói.",
      "fix": "ultimately",
      "example": "Tuần 3 – Task 2/24, Q5",
      "status": "OPEN"
    },
    {
      "stt": 36,
      "date": "2026-09-10",
      "skill": "Speaking",
      "id": "SPEAK_06",
      "original": "I mean I saw some terrible public children in the past.",
      "cause": "Chưa nhận diện đúng filler dùng để lấy thời gian suy nghĩ.",
      "fix": "let me see",
      "example": "Tuần 3 – Task 3/24, Q2",
      "status": "OPEN"
    },
    {
      "stt": 37,
      "date": "2026-09-10",
      "skill": "Speaking",
      "id": "SPEAK_07",
      "original": "make old",
      "cause": "Chưa nhận diện đúng cụm dùng để làm rõ ý vừa nói.",
      "fix": "by that I mean",
      "example": "Tuần 3 – Task 3/24, Q3",
      "status": "OPEN"
    },
    {
      "stt": 38,
      "date": "2026-09-10",
      "skill": "Speaking",
      "id": "SPEAK_08",
      "original": "Bỏ trống",
      "cause": "Chưa nhớ linker dùng để nhắc lại ý đã nói trước đó.",
      "fix": "as I mentioned before",
      "example": "Tuần 3 – Task 3/24, Q4",
      "status": "OPEN"
    },
    {
      "stt": 39,
      "date": "2026-09-10",
      "skill": "Speaking",
      "id": "SPEAK_09",
      "original": "Bỏ trống",
      "cause": "Chưa nhớ linker dùng để nhắc lại ý đã nói.",
      "fix": "as I said",
      "example": "Tuần 3 – Task 3/24, Q5",
      "status": "OPEN"
    },
    {
      "stt": 40,
      "date": "2026-09-10",
      "skill": "Speaking",
      "id": "SPEAK_10",
      "original": "Bỏ trống",
      "cause": "Chưa biết cách paraphrase khi quên từ chuyên biệt.",
      "fix": "long, thin pieces of wood",
      "example": "Tuần 3 – Task 3/24, Q6",
      "status": "OPEN"
    },
    {
      "stt": 41,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "ARTICLE_01",
      "original": "— (zero article)",
      "cause": "Chưa nắm chắc quy tắc chọn a/the/zero article.",
      "fix": "a",
      "example": "Tuần 3 – Articles Task 3, Q3",
      "status": "OPEN"
    },
    {
      "stt": 42,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "ARTICLE_02",
      "original": "the",
      "cause": "Chưa nắm chắc quy tắc chọn a/the/zero article.",
      "fix": "a",
      "example": "Tuần 3 – Articles Task 3, Q5",
      "status": "OPEN"
    },
    {
      "stt": 43,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "ARTICLE_03",
      "original": "the",
      "cause": "Chưa nắm chắc quy tắc zero article.",
      "fix": "— (zero article)",
      "example": "Tuần 3 – Articles Task 3, Q8",
      "status": "OPEN"
    },
    {
      "stt": 44,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "ARTICLE_04",
      "original": "the colorful shops",
      "cause": "Đọc sai đề / chưa nắm lý thuyết bài mạo từ.",
      "fix": "The Czech Republic",
      "example": "Tuần 3 – Articles Task 4, Q3",
      "status": "OPEN"
    },
    {
      "stt": 45,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "ARTICLE_05",
      "original": "chooses",
      "cause": "Đọc sai đề / chưa nắm lý thuyết bài mạo từ.",
      "fix": "a world",
      "example": "Tuần 3 – Articles Task 4, Q4",
      "status": "OPEN"
    },
    {
      "stt": 46,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "ARTICLE_06",
      "original": "the bright future",
      "cause": "Nhầm mạo từ xác định với danh từ chưa xác định.",
      "fix": "a bright future",
      "example": "Tuần 3 – Articles Task 4, Q6",
      "status": "OPEN"
    },
    {
      "stt": 47,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_01",
      "original": "g",
      "cause": "Lỗi đọc hiểu nghĩa của phrasal verb / ghép sai định nghĩa.",
      "fix": "f",
      "example": "Tuần 3 – Phrasal Verbs Task 1, Q2",
      "status": "OPEN"
    },
    {
      "stt": 48,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_02",
      "original": "b",
      "cause": "Lỗi đọc hiểu nghĩa của phrasal verb / ghép sai định nghĩa.",
      "fix": "g",
      "example": "Tuần 3 – Phrasal Verbs Task 1, Q4",
      "status": "OPEN"
    },
    {
      "stt": 49,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_03",
      "original": "a",
      "cause": "Lỗi đọc hiểu nghĩa của phrasal verb / ghép sai định nghĩa.",
      "fix": "h",
      "example": "Tuần 3 – Phrasal Verbs Task 1, Q5",
      "status": "OPEN"
    },
    {
      "stt": 50,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_04",
      "original": "g",
      "cause": "Lỗi đọc hiểu nghĩa của phrasal verb / ghép sai định nghĩa.",
      "fix": "b",
      "example": "Tuần 3 – Phrasal Verbs Task 1, Q6",
      "status": "OPEN"
    },
    {
      "stt": 51,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_05",
      "original": "f",
      "cause": "Lỗi đọc hiểu nghĩa của phrasal verb / ghép sai định nghĩa.",
      "fix": "a",
      "example": "Tuần 3 – Phrasal Verbs Task 1, Q7",
      "status": "OPEN"
    },
    {
      "stt": 52,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_06",
      "original": "h",
      "cause": "Lỗi đọc hiểu nghĩa của phrasal verb / ghép sai định nghĩa.",
      "fix": "d",
      "example": "Tuần 3 – Phrasal Verbs Task 1, Q8",
      "status": "OPEN"
    },
    {
      "stt": 53,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_07",
      "original": "word out",
      "cause": "Lỗi đọc hiểu nghĩa/ngữ cảnh của phrasal verb.",
      "fix": "working out",
      "example": "Tuần 3 – Phrasal Verbs Task 2, Q1",
      "status": "OPEN"
    },
    {
      "stt": 54,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_08",
      "original": "turn up",
      "cause": "Lỗi đọc hiểu nghĩa/ngữ cảnh của phrasal verb.",
      "fix": "pointed out",
      "example": "Tuần 3 – Phrasal Verbs Task 2, Q2",
      "status": "OPEN"
    },
    {
      "stt": 55,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_09",
      "original": "comes to",
      "cause": "Lỗi đọc hiểu nghĩa/ngữ cảnh của phrasal verb.",
      "fix": "came to",
      "example": "Tuần 3 – Phrasal Verbs Task 2, Q5",
      "status": "OPEN"
    },
    {
      "stt": 56,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_10",
      "original": "point out",
      "cause": "Lỗi đọc hiểu nghĩa/ngữ cảnh của phrasal verb.",
      "fix": "carry out",
      "example": "Tuần 3 – Phrasal Verbs Task 2, Q6",
      "status": "OPEN"
    },
    {
      "stt": 57,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_11",
      "original": "carried out",
      "cause": "Lỗi đọc hiểu nghĩa/ngữ cảnh của phrasal verb.",
      "fix": "turned out",
      "example": "Tuần 3 – Phrasal Verbs Task 2, Q7",
      "status": "OPEN"
    },
    {
      "stt": 58,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_12",
      "original": "turn out",
      "cause": "Lỗi đọc hiểu nghĩa/ngữ cảnh của phrasal verb.",
      "fix": "turned up",
      "example": "Tuần 3 – Phrasal Verbs Task 2, Q8",
      "status": "OPEN"
    },
    {
      "stt": 59,
      "date": "2026-09-11",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_13",
      "original": "most of",
      "cause": "Nhầm cụm thường với phrasal verb; chưa nhận biết đúng cách sử dụng.",
      "fix": "bring up",
      "example": "Tuần 3 – Phrasal Verbs Task 3, Q3",
      "status": "OPEN"
    },
    {
      "stt": 60,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_17",
      "original": "B",
      "cause": "Matching Information: định vị sai đoạn / không nhận ra paraphrase.",
      "fix": "C",
      "example": "Tuần 3 – Reading Passage 2, Q14",
      "status": "OPEN"
    },
    {
      "stt": 61,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_18",
      "original": "A",
      "cause": "Matching Information: định vị sai đoạn / không nhận ra paraphrase.",
      "fix": "G",
      "example": "Tuần 3 – Reading Passage 2, Q15",
      "status": "OPEN"
    },
    {
      "stt": 62,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_19",
      "original": "E",
      "cause": "Matching Information: định vị sai đoạn / bỏ lỡ ví dụ về hệ thống an ninh không đáng tin.",
      "fix": "D",
      "example": "Tuần 3 – Reading Passage 2, Q16",
      "status": "OPEN"
    },
    {
      "stt": 63,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_20",
      "original": "D",
      "cause": "Matching Information: không map 'hastily drawn' với 'dashed off in two seconds'.",
      "fix": "B",
      "example": "Tuần 3 – Reading Passage 2, Q17",
      "status": "OPEN"
    },
    {
      "stt": 64,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_21",
      "original": "C",
      "cause": "Matching Information: không nhận ra số liệu 3% → 30% là bằng chứng cải thiện recognition.",
      "fix": "F",
      "example": "Tuần 3 – Reading Passage 2, Q18",
      "status": "OPEN"
    },
    {
      "stt": 65,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_22",
      "original": "F",
      "cause": "Matching Information: bỏ lỡ phép so sánh facial recognition với thumbprint.",
      "fix": "D",
      "example": "Tuần 3 – Reading Passage 2, Q19",
      "status": "OPEN"
    },
    {
      "stt": 66,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_23",
      "original": "A",
      "cause": "Matching People: gán sai phát biểu cho nhân vật; không bám cụm 'instantly'.",
      "fix": "B",
      "example": "Tuần 3 – Reading Passage 2, Q20",
      "status": "OPEN"
    },
    {
      "stt": 67,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_24",
      "original": "C",
      "cause": "Matching People: gán sai quan điểm; không bám câu 'That's wrong'.",
      "fix": "B",
      "example": "Tuần 3 – Reading Passage 2, Q22",
      "status": "OPEN"
    },
    {
      "stt": 68,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_25",
      "original": "B",
      "cause": "Matching People: không nhận ra 'varying stages' và 'most recognizable to them'.",
      "fix": "A",
      "example": "Tuần 3 – Reading Passage 2, Q23",
      "status": "OPEN"
    },
    {
      "stt": 69,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_26",
      "original": "Bỏ trống",
      "cause": "Summary Completion: bỏ trống; chưa xác định noun phrase theo 'what he terms'.",
      "fix": "Hirschfeld attributes",
      "example": "Tuần 3 – Reading Passage 2, Q24",
      "status": "OPEN"
    },
    {
      "stt": 70,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_27",
      "original": "Bỏ trống",
      "cause": "Summary Completion: bỏ trống; chưa xác định danh từ số ít sau 'an'.",
      "fix": "automated system",
      "example": "Tuần 3 – Reading Passage 2, Q25",
      "status": "OPEN"
    },
    {
      "stt": 71,
      "date": "2026-09-12",
      "skill": "Reading",
      "id": "READ_28",
      "original": "Bỏ trống",
      "cause": "Summary Completion: bỏ trống; chưa xác định từ bổ nghĩa cho 'features'.",
      "fix": "exaggerated",
      "example": "Tuần 3 – Reading Passage 2, Q26",
      "status": "OPEN"
    },
    {
      "stt": 72,
      "date": "2026-09-18",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_14",
      "original": "Chọn sai",
      "cause": "Chưa phân biệt come down to = cuối cùng quy về/cốt lõi nằm ở một nguyên nhân.",
      "fix": "came down to",
      "example": "Tuần 4 – Phrasal Verbs Mini Test, Q11",
      "status": "OPEN"
    },
    {
      "stt": 73,
      "date": "2026-09-18",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_15",
      "original": "Chọn sai",
      "cause": "Chưa nhớ turn up = xuất hiện, đặc biệt khi một lỗi/vấn đề bất ngờ xuất hiện.",
      "fix": "turned up",
      "example": "Tuần 4 – Phrasal Verbs Mini Test, Q12",
      "status": "OPEN"
    },
    {
      "stt": 74,
      "date": "2026-09-18",
      "skill": "Grammar / Vocab",
      "id": "PHRASAL_16",
      "original": "Chọn sai",
      "cause": "Chưa nhớ pick out = nhận ra/chọn ra một phần tử hoặc mẫu nổi bật giữa nhiều lựa chọn.",
      "fix": "picked out",
      "example": "Tuần 4 – Phrasal Verbs Mini Test, Q13",
      "status": "OPEN"
    }
  ],
  "weeks": [
    {
      "week": "Tuần 1",
      "month": "Tháng 1",
      "total": 7,
      "completed": 7,
      "plannedMinutes": 300,
      "completedMinutes": 300,
      "bugUpdates": 1,
      "skills": [
        "Listening",
        "Reading",
        "Writing",
        "Speaking",
        "Grammar / Vocab",
        "Deep Study (Học Sâu)",
        "Review & Evaluation"
      ],
      "notes": [
        "Lỗi nghe đánh vần, ngày tháng, xác định từ khóa cần nghe, ",
        "Không hiểu đề đang yêu cầu làm gì nên sai nhiều",
        "Cần ôn lại toàn bộ nội dung",
        "Không có file nghe bt2/trang 14 và cần hiểu hơn về cách dùng Used to and would",
        "SAI nhiều , xem lại Appendix: words + dependent prepositions (124) và  Danh mục từ vựng (113 - 114)",
        "Xem lại dàn ý . BÀI TESTING LISTENING CHỈ ĐÚNG 4/40 . Không bắt được keyword , nghe đánh phần, nghe số điện thoại, chỉ đường, Nghe đoạn hội thoại dài sai. "
      ]
    },
    {
      "week": "Tuần 2",
      "month": "Tháng 1",
      "total": 7,
      "completed": 2,
      "plannedMinutes": 300,
      "completedMinutes": 60,
      "bugUpdates": 1,
      "skills": [
        "Reading",
        "Writing"
      ],
      "notes": []
    },
    {
      "week": "Tuần 3",
      "month": "Tháng 1",
      "total": 7,
      "completed": 6,
      "plannedMinutes": 300,
      "completedMinutes": 270,
      "bugUpdates": 6,
      "skills": [
        "Listening",
        "Reading",
        "Writing",
        "Speaking",
        "Deep Study (Học Sâu)",
        "Review & Evaluation"
      ],
      "notes": [
        "Xem lại bố cục và cách phát triển ý, Các cấu trúc sẽ áp dụng trong Topic",
        "Xem lại các lỗi sai , chưa hiểu tại sao sai"
      ]
    },
    {
      "week": "Tuần 4",
      "month": "Tháng 1",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 5",
      "month": "Tháng 2",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 6",
      "month": "Tháng 2",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 7",
      "month": "Tháng 2",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 8",
      "month": "Tháng 2",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 9",
      "month": "Tháng 3",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 10",
      "month": "Tháng 3",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 11",
      "month": "Tháng 3",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 12",
      "month": "Tháng 3",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 13",
      "month": "Tháng 4",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 14",
      "month": "Tháng 4",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 15",
      "month": "Tháng 4",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 16",
      "month": "Tháng 4",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 17",
      "month": "Tháng 5",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 18",
      "month": "Tháng 5",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 19",
      "month": "Tháng 5",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 20",
      "month": "Tháng 5",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 21",
      "month": "Tháng 6",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 22",
      "month": "Tháng 6",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 23",
      "month": "Tháng 6",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    },
    {
      "week": "Tuần 24",
      "month": "Tháng 6",
      "total": 7,
      "completed": 0,
      "plannedMinutes": 300,
      "completedMinutes": 0,
      "bugUpdates": 0,
      "skills": [],
      "notes": []
    }
  ],
  "tests": [
    {
      "label": "Tuần 1 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": "4",
      "listeningBand": "0.0",
      "readingRaw": "0",
      "readingBand": "0.0",
      "writingBand": "0.0",
      "speakingBand": "0.0",
      "average": "0.00",
      "overall": "0.0",
      "conclusion": "ĐỎ - Lặp Lại Tháng/Tìm Sửa"
    },
    {
      "label": "Tuần 2 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 3 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 4 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tháng 1 - Full Mock Test",
      "type": "Full Mock Test",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 5 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 6 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 7 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 8 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tháng 2 - Full Mock Test",
      "type": "Full Mock Test",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 9 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 10 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 11 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 12 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tháng 3 - Full Mock Test",
      "type": "Full Mock Test",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 13 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 14 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 15 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 16 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tháng 4 - Full Mock Test",
      "type": "Full Mock Test",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 17 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 18 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 19 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 20 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tháng 5 - Full Mock Test",
      "type": "Full Mock Test",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 21 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 22 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 23 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tuần 24 - Mini Test",
      "type": "Mini Test (L/R)",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    },
    {
      "label": "Tháng 6 - Full Mock Test",
      "type": "Full Mock Test",
      "listeningRaw": null,
      "listeningBand": null,
      "readingRaw": null,
      "readingBand": null,
      "writingBand": null,
      "speakingBand": null,
      "average": null,
      "overall": null,
      "conclusion": "Chưa Đủ Điểm"
    }
  ],
  "theory": {
    "ARTICLE": {
      "label": "Mạo từ",
      "source": "Complete IELTS — Nouns & articles, tr. 27; Language reference, tr. 120",
      "tip": "Chạy 3 câu hỏi: danh từ có đếm được không, đang nói chung hay cụ thể, người đọc đã biết đối tượng chưa? Dùng a/an cho danh từ số ít chưa xác định; the cho đối tượng cụ thể; Ø cho danh từ số nhiều/không đếm được mang nghĩa chung."
    },
    "PHRASAL": {
      "label": "Phrasal verbs",
      "source": "Complete IELTS — Unit 2, tr. 22; Language reference, tr. 115–116",
      "tip": "Học cả cụm trong ngữ cảnh, không học từng từ. Xác định verb + particle có tách được không và đặt object đúng vị trí; kiểm tra nghĩa bằng learner’s dictionary trước khi tự đặt câu."
    },
    "PREP": {
      "label": "Dependent prepositions",
      "source": "Complete IELTS — Language reference, tr. 112; Appendix, tr. 123–127",
      "tip": "Không có quy tắc đoán chắc giới từ. Học word + preposition như một chunk; sau giới từ dùng noun, pronoun hoặc V-ing, rồi đặt một câu gắn với ngữ cảnh IT của bạn."
    },
    "TENSE": {
      "label": "Thì động từ",
      "source": "Complete IELTS — Language reference, tr. 114–119",
      "tip": "Xác định timeline trước khi chia thì. Dùng Past Simple cho sự kiện đã kết thúc; Past Perfect cho hành động xảy ra trước một mốc quá khứ khác; kiểm tra V2/V3 của động từ bất quy tắc."
    },
    "READ": {
      "label": "Reading & paraphrase",
      "source": "Complete IELTS — Unit 1–2, tr. 10–13; ghi chú IETLS",
      "tip": "Theo flow: Question → keyword → dự đoán paraphrase → scan → đọc 2–3 câu quanh evidence → xác nhận. Với Summary Completion, đoán từ loại trước và chép đúng từ trong passage."
    },
    "SPEAK": {
      "label": "Speaking flow",
      "source": "Complete IELTS — Unit 2, tr. 23–24; Speaking reference, tr. 97–100",
      "tip": "Dùng chunks để giữ mạch nói: let me see, by that I mean, as I mentioned before. Ghi âm 1:30–2:00, nghe lại filler và thử nói lần hai rõ hơn."
    },
    "LIST": {
      "label": "Listening accuracy",
      "source": "Complete IELTS — Unit 1, tr. 9; Recording scripts, tr. 149",
      "tip": "Trước khi nghe, dự đoán loại từ và target. Khi nghe, phân biệt từ được nhắc tới với thông tin được xác nhận; sau bài, dùng script để đánh dấu distractor và lỗi spelling."
    }
  },
  "todayExercises": [
    {
      "prompt": "The final cause of the slow build ___ poor caching.",
      "answer": "came down to",
      "hint": "cốt lõi/quy về một nguyên nhân"
    },
    {
      "prompt": "A new production bug ___ after deployment.",
      "answer": "turned up",
      "hint": "xuất hiện bất ngờ"
    },
    {
      "prompt": "Can you ___ the invalid records in this dataset?",
      "answer": "pick out",
      "hint": "nhận ra/chọn ra giữa nhiều mục"
    }
  ]
};


